### PR TITLE
Fix handling of barcodes with multiple leading zeros

### LINKED ISSUE #701: (bug) not matching Barcodes with leading zeros
If I scan products like https://openfoodfacts.org/product/0031146262571 (or other barcodes starting with (multible) 0) Waistline asks every time to import the food, but never adding it to the dairy or selecting the existing Entry.
May a string/int casting issue while scanning?

### LINKED ISSUE #867: [BUG] Barcode scanner does not find matches in local database when UPC begins in zero
Sometimes the values returned in a scan are inaccurate, and I have to correct them when saving to my local database. However, after saving locally, scanning still only searches the internet. It would be nice to be able to match the locally-saved values with matching UPC codes.

### PR DESCRIPTION
**Pull request by EmilJunker**
This implements the suggestion I made in https://github.com/davidhealey/waistline/pull/868#issuecomment-2465065746 and also addresses the concerns raised in https://github.com/davidhealey/waistline/pull/868#issuecomment-2465490929 by keeping the original barcode (with all leading zeros) for display purposes.

Fixes #701.
Fixes #867.
Closes #868.

### CODE REVIEW

File: www/assets/js/db-handler.js [hunk 1]
```diff
@@ -174,6 +174,36 @@ var dbHandler = {
...
+
+            if (cursor) {
+              let value = cursor.value;
+
+              if (value.barcode !== undefined) {
+                if (value.barcode.startsWith("0")) {
+                  value.originalBarcode = value.barcode;
+                  value.barcode = value.barcode.substring(1);
+                }
+                if (value.barcode.startsWith("fdcId_")) {
```
Comment (davidhealey) [inline www/assets/js/db-handler.js:193]: I believe the "fdcId" prefix is to avoid clashes with barcodes from other systems such as open food facts - although it's been so long since it was written that I can't remember for certain. Do you think we'll run into any issues by removing the prefix?

Comment (EmilJunker) [reply www/assets/js/db-handler.js:193]: I only remove it for the `originalBarcode` property which is used for displaying and searching. The `barcode` property still has the prefix.

Comment (davidhealey) [reply www/assets/js/db-handler.js:193]: Ah ok, gotcha! Time for a new release, or do you have some more commits to make first?

Comment (EmilJunker) [reply www/assets/js/db-handler.js:193]: In short, items from OFF will be stored like this:

```
barcode: "<barcode-without-leading-zero>"
originalBarcode: "<barcode-including-leading-zero>"
```

And items from USDA will be stored like this:

```
barcode: "fdcId_<id>"
originalBarcode: "<id>"
```

Comment (EmilJunker) [reply www/assets/js/db-handler.js:193]: > Time for a new release, or do you have some more commits to make first?

I'm done for the time being, you can go ahead with the release 🚀

Comment (davidhealey) [reply www/assets/js/db-handler.js:193]: Thanks as always

**Comment by davidhealey** [comment]
It's been ages since I compiled so I'm setting up a new VM for it, can you remember which version of Cordova Android I should be using?

**Comment by EmilJunker** [comment]
@davidhealey It should be cordova 12.0.0 and cordova-android 12.0.1
